language: rust
sudo: required
dist: xenial
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-7
    packages:
      - llvm-7

cache: cargo
rust: nightly

before_script:
  - rustup component add clippy-preview rustfmt-preview

script:
  - cargo clean
  - cargo build
  - cargo fmt --all -- --write-mode=diff
  - cargo clippy
  - cargo test

before_cache:
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
