[package]
name = "expressi"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
build = "build.rs"

[dependencies]
cranelift = "0.18.1"
cranelift-module = "0.18.1"
cranelift-simplejit = "0.18.1"
clap = "2.32.0"

[build-dependencies]
peg = "0.5"
